version: '3.9'

services:
  db:
    image: postgres:14.1-alpine
    container_name: pg14
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      TZ: 'Asia/Tokyo'
    hostname: localhost
    restart: always
    user: postgres

volumes:
  db_data:
    external: false
