version: '3.9'

services:
  roach-0:
    container_name: roach-0
    hostname: roach-0
    image: cockroachdb/cockroach:latest
    command: start-single-node --cluster-name=roach-cluster --logtostderr=WARNING --log-file-verbosity=WARNING --insecure

  roach-1:
    container_name: roach-1
    hostname: roach-1
    image: cockroachdb/cockroach:latest
    command: start --cluster-name=roach-cluster --logtostderr=WARNING --log-file-verbosity=WARNING --insecure --join=roach-0
    depends_on:
      - roach-0

  roach-2:
    container_name: roach-2
    hostname: roach-2
    image: cockroachdb/cockroach:latest
    command: start --cluster-name=roach-cluster --logtostderr=WARNING --log-file-verbosity=WARNING --insecure --join=roach-0
    depends_on:
      - roach-0

  lb:
    container_name: lb
    hostname: lb
    build: ./nginx
    ports:
      - 26257:26257
      - 8080:8080
    depends_on:
      - roach-0
      - roach-1
      - roach-2
